# Table of Contents
 <p>

Preparation for workshop: data preparation

In [1]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [2]:
iris = load_iris()
usage_df = pd.DataFrame(iris.data, columns = iris.feature_names)
usage_df['target'] = iris.target
usage_df.shape

(150, 5)

In [3]:
usage_df.target.value_counts()

2    50
1    50
0    50
Name: target, dtype: int64

In [4]:
usage_df.columns = ['12am_8am','8am_2pm','2pm_9pm','9pm_12am','target']

# swap columns to make data more realistic
usage_df = usage_df[['8am_2pm','2pm_9pm','12am_8am','9pm_12am','target']]
usage_df.columns = ['12am_8am','8am_2pm','2pm_9pm','9pm_12am','target']

# add check column
usage_df['total_kwh'] = usage_df[['12am_8am','8am_2pm','2pm_9pm','9pm_12am']].apply(lambda x: x.sum(), axis=1)

In [5]:
# to make it more realistic, we need to get total value to around 6-7kwh per day
# half most measurements
usage_df.iloc[:,0] = round(usage_df.iloc[:,0]*(0.5),1)
#usage_df.iloc[:,1] = round(usage_df.iloc[:,1]*(0.1),1)
usage_df.iloc[:,2] = round(usage_df.iloc[:,2]*(0.5),1)

# update total
usage_df['total_kwh'] = usage_df[['12am_8am','8am_2pm','2pm_9pm','9pm_12am']].apply(lambda x: x.sum(), axis=1)

usage_df.head(2)

12am_8am  8am_2pm  2pm_9pm  9pm_12am  target  total_kwh
0       1.8      1.4      2.6       0.2       0        6.0
1       1.5      1.4      2.4       0.2       0        5.5

In [6]:
usage_df.tail(2)

12am_8am  8am_2pm  2pm_9pm  9pm_12am  target  total_kwh
148       1.7      5.4      3.1       2.3       2       12.5
149       1.5      5.1      3.0       1.8       2       11.4

In [7]:
# check
usage_df.total_kwh.hist();

In [8]:
# add some null values

sample_cols = np.random.choice([0,1,2,3],size=10,replace=True)
sample_rows = np.random.choice(usage_df.index,10,replace=False)

for pos in np.arange(len(sample_cols)):
    usage_df.iloc[sample_rows[pos],sample_cols[pos]] = np.nan

sample_cols,sample_rows

(array([3, 0, 0, 3, 2, 2, 2, 2, 0, 3]),
 array([135, 125,  49,  68,  14,  92, 127,  35,  42,   3]))

In [9]:
# check
np.where(usage_df.isnull())

(array([  3,  14,  35,  42,  49,  68,  92, 125, 127, 135]),
 array([3, 2, 2, 0, 0, 3, 2, 0, 2, 3]))

In [10]:
# shuffle data and reset index
usage_df = usage_df.sample(frac=1).reset_index(drop=True)

In [13]:
usage_df.tail(2)

12am_8am  8am_2pm  2pm_9pm  9pm_12am  target  total_kwh
148       1.7      1.5      2.7       0.4       0        6.3
149       1.7      1.7      2.7       0.2       0        6.3

In [14]:
path = '/Users/elenahensinger/Documents/PROJECTS/2019/09_WorkshopWednesdays_W1/datasets'

usage_df[['12am_8am','8am_2pm','2pm_9pm','9pm_12am']].to_csv(path + '/workshop_data1.csv')